client1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('clientapp.urls')),
]

# For Media Dir variables
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = urlpatterns + static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

clientapp/urls.py
from django.urls import path,include
from . import views

# Namespace
app_name = 'emp'

# URL Patterns
urlpatterns = [
    # path('', views.welcome_page, name='welcome'),
    #path('login/', views.login_page, name='login'),
    path('', views.server_page, name='server'),
    # path('client/', views.user_login, name='client'),
    #path('dashboard/',views.dashboard,name = 'dashboard'),
    path('start/', views.start_work, name='start_work'),
    path('end/<int:session_id>/', views.end_work, name='end_work'),
    #path('pause/<int:session_id>/', views.pause_work, name='pause_work'),
    #path('resume/<int:session_id>/', views.resume_work, name='resume_work'),
    #path('update-description/<int:session_id>/', views.update_session_description, name='update_session_description'),
    path('server-login/',views.server_login,name = 'server_login'),
    #path('login/',views.user_login,name = 'user_login'),
    path('logout/',views.user_logout ,name = 'user_logout'),
    #path('register/',views.register,name = 'register'),
    #path('goodbye/',views.goodbye,name = 'goodbye'),
    path('employee_selection/', views.employee_selection, name='employee_selection'),
    #path('password_login/', views.password_login, name='password_login'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('machine-selection/', views.machine_selection, name='machine_selection'),
    path('select-machine/', views.select_machine, name='select_machine'),
    path('complaint_selection<str:page_id>/', views.complaint_selection, name='complaint_selection'),
    path('logout_and_redirect/', views.logout_and_redirect, name='logout_and_redirect'),
    path('save_complaint/', views.save_complaint, name='save_complaint'),
    path('tempend/', views.temp_end_work, name='temp_end_work'), # temp fix
]

clientapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


def user_directory_path(self, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return "user_{0}/{1}".format(self.user.id, filename)


class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    photo = models.ImageField(upload_to=user_directory_path, null=True, blank=True)
    is_working = models.BooleanField(default=False)
     

    def __str__(self):
        return "profile {}".format(self.user.username)


class WorkSession(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField(null=True, blank=True)
    #description = models.TextField(blank=True, null=True)
    #paused = models.BooleanField(default=False)
    #pause_time = models.DateTimeField(null=True, blank=True)
    machine = models.CharField(max_length=10, blank=True, null=True)
    complaint = models.CharField(max_length=255, blank=True, null=True)
    issue = models.CharField(max_length=255, blank=True, null=True)
    confirmed = models.BooleanField(default=False)  # Add this to store confirmation status

    def __str__(self):
        return f"{self.employee.name} from {self.start_time} to {self.end_time if self.end_time else 'Ongoing'}"


    def duration(self):
        """Calculate duration of the work session in a readable format."""
        if self.end_time:
            duration = self.end_time - self.start_time
        else:
            duration = timezone.now() - self.start_time

        total_seconds = duration.total_seconds()
        hours, remainder = divmod(total_seconds, 3600)
        minutes, seconds = divmod(remainder, 60)
        return f"{int(hours)}h {int(minutes)}m"

clientapp/forms.py
from django import forms
from django.contrib.auth.models import User

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Field, Layout, Row, Column, Submit, Reset
from crispy_forms.bootstrap import PrependedText


class LoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(label="Password", widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)
    photo = forms.ImageField(required=False)

    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
            "password",
            "confirm_password",
            "photo",
        ]
        labels = {
            "username": "Username",
            "first_name": "First Name",
            "last_name": "Last Name",
            "email": "Email Address",
            "password": "Password",
            "confirm_password": "Confirm Password",
            "photo": "Profile Picture",
        }

    def __init__(self, *args, **kwargs):
        super(UserRegistrationForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            PrependedText("username", "@", placeholder="user_name"),
            Row(
                Column("password", css_class="form-group col"),
                Column("confirm_password", css_class="form-group col"),
                css_class="form-row",
            ),
            Row(
                Column("first_name", css_class="form-group col"),
                Column("last_name", css_class="form-group col"),
                css_class="form-row",
            ),
            "email",
            "photo",
            Submit("submit", "Register", css_class="btn btn-primary"),
            Reset("reset", "Reset", css_class="btn btn-secondary"),
        )

    def clean_confirm_password(self):
        password = self.cleaned_data["password"]
        confirm_password = self.cleaned_data["confirm_password"]
        if password != confirm_password:
            raise forms.ValidationError("Password Mismatch")
        else:
            return confirm_password

class PasswordResetForm(forms.Form):
    new_password = forms.CharField(widget=forms.PasswordInput, label='New Password')
    confirm_password = forms.CharField(widget=forms.PasswordInput, label='Confirm New Password')

    def clean(self):
        cleaned_data = super().clean()
        new_password = cleaned_data.get('new_password')
        confirm_password = cleaned_data.get('confirm_password')

        if new_password and confirm_password and new_password != confirm_password:
            raise forms.ValidationError("Passwords do not match.")

clientapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Employee, WorkSession
from .forms import LoginForm, UserRegistrationForm
from django.contrib.auth import authenticate, logout, login
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils import timezone
from itertools import groupby
from datetime import date
import json

def server_login(request):
    return render(request, "server/login.html")

def login_page(request):
    return render(request, "emp/login.html")

def server_page(request):
    return render(request, "server/welcome.html")

def client_page():
    return HttpResponseRedirect(reverse("emp:employee_selection"))

def register(request):
    if request.user.is_authenticated:
        return HttpResponse("First logout")

    if request.method == "POST":
        form = UserRegistrationForm(request.POST, request.FILES)

        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data["password"])
            user.save()

            Employee.objects.create(
                user=user,
                photo=request.FILES.get("photo"),
            )

            return HttpResponseRedirect(reverse("emp:server"))
    else:
        form = UserRegistrationForm()

    context = {"form": form}
    return render(request, "emp/register.html", context)

@login_required
def start_work(request):
    employee = Employee.objects.get(user=request.user)
    employee.is_working = True

    description = request.POST.get("description", "")
    machine_number = request.POST.get("machine", None)

    WorkSession.objects.create(
        employee=employee,
        start_time=timezone.now(),
        description=description,
        machine=machine_number
    )

    response = redirect("emp:dashboard")
    if machine_number:
        response.set_cookie("machine", machine_number, max_age=30*24*60*60)  # 30 days
    return response

@login_required
def temp_end_work(request):
    employee = Employee.objects.get(user=request.user)
    work_session = WorkSession.objects.filter(employee=employee, end_time__isnull=True).last()

    if work_session:
        work_session.end_time = timezone.now()
        work_session.save()

    employee.is_working = False
    employee.save()

    logout(request)
    return redirect('emp:employee_selection')

@login_required
def end_work(request, session_id):
    employee = Employee.objects.get(user=request.user)
    employee.is_working = False

    session = WorkSession.objects.get(id=session_id)
    session.end_time = timezone.now()
    session.save()
    return redirect("emp:dashboard")

@login_required
def pause_work(request, session_id):
    session = WorkSession.objects.get(id=session_id)
    session.paused = True
    session.pause_time = timezone.now()
    session.save()
    return redirect("emp:dashboard")

@login_required
def resume_work(request, session_id):
    session = WorkSession.objects.get(id=session_id)
    if session.paused:
        pause_duration = timezone.now() - session.pause_time
        session.start_time += pause_duration
        session.paused = False
        session.pause_time = None
        session.save()
    return redirect("emp:dashboard")

@login_required
def update_session_description(request, session_id):
    if request.method == "POST":
        session = get_object_or_404(WorkSession, id=session_id)
        session.description = request.POST.get("description", "")
        session.save()
    return redirect("emp:dashboard")

@login_required
def dashboard(request):
    if request.user.is_authenticated:
        employee = Employee.objects.get(user=request.user)
        sessions = WorkSession.objects.filter(employee=employee).order_by("-start_time")

        sessions_grouped_by_day = {}
        for day, group in groupby(sessions, key=lambda s: s.start_time.date()):
            sessions_grouped_by_day[day] = list(group)

        latest_session = sessions.first()
        today = date.today()

        context = {
            "latest_session": latest_session,
            "sessions_grouped_by_day": sessions_grouped_by_day,
            "today": today,
        }
        return render(request, "emp/dashboard.html", context)
    else:
        return HttpResponseRedirect(reverse("emp:employee_selection"))

@login_required
def user_logout(request):
    username = request.user.first_name + " " + request.user.last_name
    logout(request)
    return HttpResponseRedirect(reverse("emp:goodbye") + f"?username={username}")

def goodbye(request):
    username = request.GET.get("username")
    if not username:
        username = "User"
    return render(request, "emp/goodbye.html", {"username": username})

def machine_selection(request):
    context = {
        'range': range(1, 25)  # Machines M1 to M24
    }

    # Get the current employee
    employee = Employee.objects.get(user=request.user)
    # Get the last work session
    work_session = WorkSession.objects.filter(employee=employee, end_time__isnull=True).last()

    if work_session:
        context['issue'] = work_session.issue  # Retrieve the current issue from the work session

    return render(request, 'emp/machine_selection.html', context)

def select_machine(request):
    if request.method == 'POST':
        selected_machine = request.POST.get('machine')
        if not selected_machine:
            return redirect('emp:machine_selection')  # Handle no selection case

        try:
            employee = Employee.objects.get(user=request.user)
        except Employee.DoesNotExist:
            return redirect('emp:machine_selection')  # Handle case where Employee is not found

        # Create a WorkSession
        WorkSession.objects.create(
            employee=employee,
            start_time=timezone.now(),
            machine=selected_machine  # Assign selected machine
        )

        # Redirect to the complaint_selection page with the selected machine number
        return redirect('emp:complaint_selection', page_id=selected_machine)

    return redirect('emp:machine_selection')

def complaint_selection(request, page_id):
    # Retrieve the last work session for the current employee
    employee = Employee.objects.get(user=request.user)
    work_session = WorkSession.objects.filter(employee=employee, end_time__isnull=True).last()

    selected_issue = None
    if work_session and work_session.issue:
        selected_issue = work_session.issue  # Fetch the issue from the work session

    complaints = range(1, 13)  # Example complaints; replace with your actual query or model

    context = {
        'page_id': page_id,
        'complaints': complaints,
        'selected_issue': selected_issue,  # Pass the selected issue to the template
    }

    return render(request, 'emp/complaint_selection.html', context)

def employee_selection(request):
    if request.method == "POST":
        # Get the username from hidden input field after employee selection
        username = request.POST.get("username", "")
        password = request.POST.get("password", "")

        # Authenticate the user with the provided password
        user = authenticate(request, username=username, password=password)

        if user:
            if user.is_active:
                # Log in the user and redirect to the machine selection page
                login(request, user)
                request.session.pop('logged_out_employee_username', None)  # Clear the logged_out_employee_username variable
                return HttpResponseRedirect(reverse("emp:machine_selection"))
            else:
                return HttpResponse("User is not active")
        else:
            # Show error if authentication fails
            messages.error(request, "Invalid password. Please try again.")
            return HttpResponseRedirect(reverse("emp:employee_selection"))

    # Fetch all employees to display in the profile selection page
    employees = Employee.objects.all()
    employees_with_latest_issues = []
    for employee in employees:
        latest_work_session = WorkSession.objects.filter(employee=employee).order_by('-start_time').first()
        employees_with_latest_issues.append({
            'employee': employee,
            'session': latest_work_session
        })

    logged_out_employee_username = request.session.get('logged_out_employee_username', None)
    return render(request, 'emp/employee_selection.html', {
        'employees_with_latest_issues': employees_with_latest_issues,
        'logged_out_employee_username': logged_out_employee_username
    })

def logout_and_redirect(request):
    # Get the username of the logged-out employee and store it in the session
    logged_out_employee_username = request.user.username
    request.session['logged_out_employee_username'] = logged_out_employee_username

    employee = Employee.objects.get(user=request.user)
    employee.is_working = True
    employee.save()

    # Perform the logout
    logout(request)
    return redirect('emp:employee_selection')



def save_complaint(request):
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            complaint = data.get('complaint')
            issue = data.get('issue')

            employee = Employee.objects.get(user=request.user)
            work_session = WorkSession.objects.filter(employee=employee, end_time__isnull=True).last()

            if work_session:
                work_session.complaint = complaint
                work_session.issue = issue

clientapp/templates/server/base.html
{% load static %}
<!DOCTYPE html>
<html>

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
    <title>{% block title %}Lotus Pvt Ltd{% endblock %}</title>

    <script src="{% static 'bootstrap/bootstrap.min.js' %} "></script>
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.min.css' %} ">
    <link rel="stylesheet" href="{% static 'font-awesome/all.min.css' %} ">
    <link rel="stylesheet" href="{% static 'styles/app.css' %}" type="text/css" />
  </head>

  <body data-bs-theme="dark">

    <!-- SIDE NAVBAR -->
    <!-- <nav class="navbar bg-body-tertiary fixed-top"> -->
    <nav class="navbar bg-body-tertiary sticky-top">
      <div class="container-fluid">
        <!-- LEFT SIDE: BRAND -->
        <a class="navbar-brand" href="">Lotus Pvt Ltd</a>
        <!-- TOGGLE DARK MODE - LIGHT MODE -->
        <button id="themeToggle" class="btn mx-2 fas"></button>
        <!-- RIGHT SIDE: TOGGLER -->
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">

          <!-- SIDEBAR - HEADER -->
          <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Profile Details</h5>
            <!-- TOGGLE SIDEBAR -->
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
          </div>

          <div class="offcanvas-body text-center">

            <!-- SIDEBAR - PROFILE -->
            <div>
              <a href="#">
                {% if request.user.employee.photo %}
                <img src="{{ request.user.employee.photo.url }}" width="65%" height="65%" class="rounded-circle" alt="Custom Profile Pic">
                {% else %}
                <img src="{% static 'default.png' %}" width="65%" height="65%" class="rounded-circle" alt="Default Profile Pic">
                {% endif %}
              </a>
              <p class="mt-3 h4">{{ request.user.first_name }} {{ request.user.last_name }}</p>
              <p class="mb-3">@{{ request.user.username }}</p>
            </div>

            <div>
              <!-- RIGHT SIDE: PROFILE RELATED LINKS -->
              {% if request.user.is_authenticated %}
              <a href="{% url 'emp:user_logout' %}" class="btn btn-danger"><i class="fas fa-right-from-bracket"></i> Logout</a>
              {% else %}
              <a href="{% url 'emp:login' %}" class="btn btn-primary"><i class="fas fa-right-to-bracket"></i> Login</a>
              {% endif %}
            </div>

          </div>
        </div>
      </div>
    </nav>


    <div class="container-fluid p-5">
      <div class="container container-fluid">
        {% block content %}
        {% endblock %}
      </div>
    </div>
    <script src="{% static 'scripts/app.js' %}"></script>
  </body>
</html>

clientapp/templates/server/dashboard.html
{% extends 'server/base.html' %}

{% block title %}{{user.username}} - {{block.super}}{% endblock %}
{% load static %}
{% load session_tags %}

{% block content %}

<!-- @MAIN CONTENT -->

<div class="col-lg-8 mb-5">
  <h4 class="display-6 text-muted my-0">Welcome to</h4>
  <h1 class="display-1 my-0">Lotus Pvt Ltd</h1>
  <p>Your trusted partner in employee management.</p>
</div>

<section class="container">

  <div class="card" style="width: 18rem;">
    <div class="display-1 text-center p-3"><i class="fas fa-user-plus"></i></div>
    <div class="card-body">
      <h5 class="card-title">Register New Employee</h5>
      <p class="card-text">Add details and register a new employee</p>
      <a href="{% url 'emp:register' %}" class="btn btn-lg btn-primary">Start</a>
    </div>
  </div>

</section>

{% endblock %}

clientapp/templates/server/login.html
{% extends 'server/base.html' %}
{% block title %}Login at - {{block.super}}{% endblock %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<h1 class="display-6">Welcome Admin!</h1>
<!-- <hr class="my-4 "> -->
<br>

<!-- AUTHENTICATION ERROR MESSAGE -->
{% if messages %}
{% for message in messages %}
<div class="alert alert-danger" role="alert">
  {{ message }}
</div>
{% endfor %}
{% endif %}

  <!-- CUSTOM LOGIN FORM -->
<form method="POST">
  {% csrf_token %}
  <!-- { { form|crispy }} -->
  <div class="container container-fluid">
    <div class="mb-4">
      <label class="form-label mb-0">Username</label>
      <input type="text" class="form-control form-control-lg" placeholder="Username" name="username">
    </div>
    <div class="mb-4">
      <label class="form-label mb-0">Password</label>
      <input type="password" class="form-control form-control-lg" placeholder="Password" name="password">
    </div>
    <div class="mb-4">
      <input type="submit" class="btn btn-primary mb-2" name="submit" value="Login">
    </div>
    <div class="links">
      <a href="{% url 'emp:register' %}">No account?</a>
      <a href="{% url 'emp:register' %}">Sign Up!</a>
    </div>
  </div>
</form>

{% endblock %}

clientapp/templates/server/welcome.html
{% extends 'server/base.html' %}
{% block title %}Welcome to {{block.super}}{% endblock %}
{% load static %}

{% block content %}
<style>
body {
  background-image: url('https://static.vecteezy.com/system/resources/thumbnails/023/308/048/small/abstract-grey-metallic-overlap-on-dark-circle-mesh-pattern-design-modern-luxury-futuristic-background-vector.jpg');
  background-repeat: no-repeat;
  background-size: cover;
}
</style>

  <!-- @MAIN CONTENT -->
<body onclick="window.location.href='{% url 'emp:server_login' %}'" style="cursor: pointer;">
  <div class="container-fluid d-flex align-items-center bg-body-tertiary border rounded-4" style="height:80vh;">
    <div class="col-lg-8 p-5">
      <h4 class="display-6 text-muted my-0">Welcome to</h4>
      <h1 class="display-1 my-0">Lotus Pvt Ltd</h1>
      <p>Your trusted partner in employee management.</p>
    </div>
  </div>
</body>

  {% endblock %}