client1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('clientapp.urls')),
]

# For Media Dir variables
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = urlpatterns + static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

clientapp/urls.py
from django.urls import path,include
from . import views

# Namespace
app_name = 'emp'

# URL Patterns
urlpatterns = [
    # path('', views.welcome_page, name='welcome'),
    #path('login/', views.login_page, name='login'),
    path('', views.server_page, name='server'),
    # path('client/', views.user_login, name='client'),
    #path('dashboard/',views.dashboard,name = 'dashboard'),
    path('start/', views.start_work, name='start_work'),
    path('end/<int:session_id>/', views.end_work, name='end_work'),
    #path('pause/<int:session_id>/', views.pause_work, name='pause_work'),
    #path('resume/<int:session_id>/', views.resume_work, name='resume_work'),
    #path('update-description/<int:session_id>/', views.update_session_description, name='update_session_description'),
    path('server-login/',views.server_login,name = 'server_login'),
    #path('login/',views.user_login,name = 'user_login'),
    path('logout/',views.user_logout ,name = 'user_logout'),
    #path('register/',views.register,name = 'register'),
    #path('goodbye/',views.goodbye,name = 'goodbye'),
    path('employee_selection/', views.employee_selection, name='employee_selection'),
    #path('password_login/', views.password_login, name='password_login'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('machine-selection/', views.machine_selection, name='machine_selection'),
    path('select-machine/', views.select_machine, name='select_machine'),
    path('complaint_selection<str:page_id>/', views.complaint_selection, name='complaint_selection'),
    path('logout_and_redirect/', views.logout_and_redirect, name='logout_and_redirect'),
    path('save_complaint/', views.save_complaint, name='save_complaint'),
    path('tempend/', views.temp_end_work, name='temp_end_work'), # temp fix
]

clientapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


def user_directory_path(self, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return "user_{0}/{1}".format(self.user.id, filename)


class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    photo = models.ImageField(upload_to=user_directory_path, null=True, blank=True)
    is_working = models.BooleanField(default=False)
     

    def __str__(self):
        return "profile {}".format(self.user.username)


class WorkSession(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField(null=True, blank=True)
    #description = models.TextField(blank=True, null=True)
    #paused = models.BooleanField(default=False)
    #pause_time = models.DateTimeField(null=True, blank=True)
    machine = models.CharField(max_length=10, blank=True, null=True)
    complaint = models.CharField(max_length=255, blank=True, null=True)
    issue = models.CharField(max_length=255, blank=True, null=True)
    confirmed = models.BooleanField(default=False)  # Add this to store confirmation status

    def __str__(self):
        return f"{self.employee.name} from {self.start_time} to {self.end_time if self.end_time else 'Ongoing'}"


    def duration(self):
        """Calculate duration of the work session in a readable format."""
        if self.end_time:
            duration = self.end_time - self.start_time
        else:
            duration = timezone.now() - self.start_time

        total_seconds = duration.total_seconds()
        hours, remainder = divmod(total_seconds, 3600)
        minutes, seconds = divmod(remainder, 60)
        return f"{int(hours)}h {int(minutes)}m"

clientapp/forms.py
from django import forms
from django.contrib.auth.models import User

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Field, Layout, Row, Column, Submit, Reset
from crispy_forms.bootstrap import PrependedText


class LoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(label="Password", widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)
    photo = forms.ImageField(required=False)

    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
            "password",
            "confirm_password",
            "photo",
        ]
        labels = {
            "username": "Username",
            "first_name": "First Name",
            "last_name": "Last Name",
            "email": "Email Address",
            "password": "Password",
            "confirm_password": "Confirm Password",
            "photo": "Profile Picture",
        }

    def __init__(self, *args, **kwargs):
        super(UserRegistrationForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            PrependedText("username", "@", placeholder="user_name"),
            Row(
                Column("password", css_class="form-group col"),
                Column("confirm_password", css_class="form-group col"),
                css_class="form-row",
            ),
            Row(
                Column("first_name", css_class="form-group col"),
                Column("last_name", css_class="form-group col"),
                css_class="form-row",
            ),
            "email",
            "photo",
            Submit("submit", "Register", css_class="btn btn-primary"),
            Reset("reset", "Reset", css_class="btn btn-secondary"),
        )

    def clean_confirm_password(self):
        password = self.cleaned_data["password"]
        confirm_password = self.cleaned_data["confirm_password"]
        if password != confirm_password:
            raise forms.ValidationError("Password Mismatch")
        else:
            return confirm_password

class PasswordResetForm(forms.Form):
    new_password = forms.CharField(widget=forms.PasswordInput, label='New Password')
    confirm_password = forms.CharField(widget=forms.PasswordInput, label='Confirm New Password')

    def clean(self):
        cleaned_data = super().clean()
        new_password = cleaned_data.get('new_password')
        confirm_password = cleaned_data.get('confirm_password')

        if new_password and confirm_password and new_password != confirm_password:
            raise forms.ValidationError("Passwords do not match.")

clientapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Employee, WorkSession
from .forms import LoginForm, UserRegistrationForm
from django.contrib.auth import authenticate, logout, login
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils import timezone
from itertools import groupby
from datetime import date
import json

def server_login(request):
    return render(request, "server/login.html")

def login_page(request):
    return render(request, "emp/login.html")

def server_page(request):
    return render(request, "server/welcome.html")

def client_page():
    return HttpResponseRedirect(reverse("emp:employee_selection"))

def register(request):
    if request.user.is_authenticated:
        return HttpResponse("First logout")

    if request.method == "POST":
        form = UserRegistrationForm(request.POST, request.FILES)

        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data["password"])
            user.save()

            Employee.objects.create(
                user=user,
                photo=request.FILES.get("photo"),
            )

            return HttpResponseRedirect(reverse("emp:server"))
    else:
        form = UserRegistrationForm()

    context = {"form": form}
    return render(request, "emp/register.html", context)

@login_required
def start_work(request):
    employee = Employee.objects.get(user=request.user)
    employee.is_working = True

    description = request.POST.get("description", "")
    machine_number = request.POST.get("machine", None)

    WorkSession.objects.create(
        employee=employee,
        start_time=timezone.now(),
        description=description,
        machine=machine_number
    )

    response = redirect("emp:dashboard")
    if machine_number:
        response.set_cookie("machine", machine_number, max_age=30*24*60*60)  # 30 days
    return response

@login_required
def temp_end_work(request):
    employee = Employee.objects.get(user=request.user)
    work_session = WorkSession.objects.filter(employee=employee, end_time__isnull=True).last()

    if work_session:
        work_session.end_time = timezone.now()
        work_session.save()

    employee.is_working = False
    employee.save()

    logout(request)
    return redirect('emp:employee_selection')

@login_required
def end_work(request, session_id):
    employee = Employee.objects.get(user=request.user)
    employee.is_working = False

    session = WorkSession.objects.get(id=session_id)
    session.end_time = timezone.now()
    session.save()
    return redirect("emp:dashboard")

@login_required
def pause_work(request, session_id):
    session = WorkSession.objects.get(id=session_id)
    session.paused = True
    session.pause_time = timezone.now()
    session.save()
    return redirect("emp:dashboard")

@login_required
def resume_work(request, session_id):
    session = WorkSession.objects.get(id=session_id)
    if session.paused:
        pause_duration = timezone.now() - session.pause_time
        session.start_time += pause_duration
        session.paused = False
        session.pause_time = None
        session.save()
    return redirect("emp:dashboard")

@login_required
def update_session_description(request, session_id):
    if request.method == "POST":
        session = get_object_or_404(WorkSession, id=session_id)
        session.description = request.POST.get("description", "")
        session.save()
    return redirect("emp:dashboard")

@login_required
def dashboard(request):
    if request.user.is_authenticated:
        employee = Employee.objects.get(user=request.user)
        sessions = WorkSession.objects.filter(employee=employee).order_by("-start_time")

        sessions_grouped_by_day = {}
        for day, group in groupby(sessions, key=lambda s: s.start_time.date()):
            sessions_grouped_by_day[day] = list(group)

        latest_session = sessions.first()
        today = date.today()

        context = {
            "latest_session": latest_session,
            "sessions_grouped_by_day": sessions_grouped_by_day,
            "today": today,
        }
        return render(request, "emp/dashboard.html", context)
    else:
        return HttpResponseRedirect(reverse("emp:employee_selection"))

@login_required
def user_logout(request):
    username = request.user.first_name + " " + request.user.last_name
    logout(request)
    return HttpResponseRedirect(reverse("emp:goodbye") + f"?username={username}")

def goodbye(request):
    username = request.GET.get("username")
    if not username:
        username = "User"
    return render(request, "emp/goodbye.html", {"username": username})

def machine_selection(request):
    context = {
        'range': range(1, 25)  # Machines M1 to M24
    }

    # Get the current employee
    employee = Employee.objects.get(user=request.user)
    # Get the last work session
    work_session = WorkSession.objects.filter(employee=employee, end_time__isnull=True).last()

    if work_session:
        context['issue'] = work_session.issue  # Retrieve the current issue from the work session

    return render(request, 'emp/machine_selection.html', context)

def select_machine(request):
    if request.method == 'POST':
        selected_machine = request.POST.get('machine')
        if not selected_machine:
            return redirect('emp:machine_selection')  # Handle no selection case

        try:
            employee = Employee.objects.get(user=request.user)
        except Employee.DoesNotExist:
            return redirect('emp:machine_selection')  # Handle case where Employee is not found

        # Create a WorkSession
        WorkSession.objects.create(
            employee=employee,
            start_time=timezone.now(),
            machine=selected_machine  # Assign selected machine
        )

        # Redirect to the complaint_selection page with the selected machine number
        return redirect('emp:complaint_selection', page_id=selected_machine)

    return redirect('emp:machine_selection')

def complaint_selection(request, page_id):
    # Retrieve the last work session for the current employee
    employee = Employee.objects.get(user=request.user)
    work_session = WorkSession.objects.filter(employee=employee, end_time__isnull=True).last()

    selected_issue = None
    if work_session and work_session.issue:
        selected_issue = work_session.issue  # Fetch the issue from the work session

    complaints = range(1, 13)  # Example complaints; replace with your actual query or model

    context = {
        'page_id': page_id,
        'complaints': complaints,
        'selected_issue': selected_issue,  # Pass the selected issue to the template
    }

    return render(request, 'emp/complaint_selection.html', context)

def employee_selection(request):
    if request.method == "POST":
        # Get the username from hidden input field after employee selection
        username = request.POST.get("username", "")
        password = request.POST.get("password", "")

        # Authenticate the user with the provided password
        user = authenticate(request, username=username, password=password)

        if user:
            if user.is_active:
                # Log in the user and redirect to the machine selection page
                login(request, user)
                request.session.pop('logged_out_employee_username', None)  # Clear the logged_out_employee_username variable
                return HttpResponseRedirect(reverse("emp:machine_selection"))
            else:
                return HttpResponse("User is not active")
        else:
            # Show error if authentication fails
            messages.error(request, "Invalid password. Please try again.")
            return HttpResponseRedirect(reverse("emp:employee_selection"))

    # Fetch all employees to display in the profile selection page
    employees = Employee.objects.all()
    employees_with_latest_issues = []
    for employee in employees:
        latest_work_session = WorkSession.objects.filter(employee=employee).order_by('-start_time').first()
        employees_with_latest_issues.append({
            'employee': employee,
            'session': latest_work_session
        })

    logged_out_employee_username = request.session.get('logged_out_employee_username', None)
    return render(request, 'emp/employee_selection.html', {
        'employees_with_latest_issues': employees_with_latest_issues,
        'logged_out_employee_username': logged_out_employee_username
    })

def logout_and_redirect(request):
    # Get the username of the logged-out employee and store it in the session
    logged_out_employee_username = request.user.username
    request.session['logged_out_employee_username'] = logged_out_employee_username

    employee = Employee.objects.get(user=request.user)
    employee.is_working = True
    employee.save()

    # Perform the logout
    logout(request)
    return redirect('emp:employee_selection')



def save_complaint(request):
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            complaint = data.get('complaint')
            issue = data.get('issue')

            employee = Employee.objects.get(user=request.user)
            work_session = WorkSession.objects.filter(employee=employee, end_time__isnull=True).last()

            if work_session:
                work_session.complaint = complaint
                work_session.issue = issue

clientapp/templates/emp/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
  <link rel="shortcut icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
  <title>{% block title %}Lotus Pvt Ltd{% endblock %}</title>

  <script src="{% static 'bootstrap/bootstrap.min.js' %} "></script>
  <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.min.css' %} ">
  <link rel="stylesheet" href="{% static 'font-awesome/all.min.css' %} ">
  <link rel="stylesheet" href="{% static 'styles/app.css' %}" type="text/css" />


  <style>
    /* Custom styles for larger text and header */
    .navbar-brand {
      font-size: 2.5rem; /* Make the "Lotus Pvt Ltd" brand text larger */
      font-weight: bold;
    }

    .navbar-text.h5 {
      font-size: 2rem; /* Larger page title text */
      font-weight: bold;
    }

    #datetime {
      font-size: 1.5rem; /* Larger date and time */
    }

    /* Increase profile name and username text size */
    .offcanvas-body .h4,
    .offcanvas-body .mb-3 {
      font-size: 1.75rem;
    }

    /* Adjust logout/login button size */
    .btn {
      font-size: 1.25rem;
    }
  </style>
</head>

<body data-bs-theme="dark">

  <!-- SIDE NAVBAR -->
  <nav class="navbar bg-body-tertiary sticky-top">
    <div class="container-fluid">
      <!-- LEFT SIDE: BRAND -->
      <a class="navbar-brand">Lotus Pvt Ltd</a>

      <!-- CENTER: PAGE TITLE -->
      <span class="navbar-text mx-auto h5">Technician Work Log</span>

      <!-- RIGHT SIDE: DATE AND TIME -->
      <span id="datetime" class="navbar-text h6 text-end"></span>

      <!-- TOGGLE DARK MODE - LIGHT MODE -->
      <button id="themeToggle" class="btn mx-2 fas"></button>

      <!-- RIGHT SIDE: TOGGLER
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">

       <!-- SIDEBAR - HEADER -->
        <!--div class="offcanvas-header">
          <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Profile Details</h5>
          <!-- TOGGLE SIDEBAR -->
          <!--button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>

        <div class="offcanvas-body text-center">

          <!-- SIDEBAR - PROFILE -->
          <!--div>
            <a href="#">
              {% if request.user.employee.photo %}
              <img src="{{ request.user.employee.photo.url }}" width="65%" height="65%" class="rounded-circle" alt="Custom Profile Pic">
              {% else %}
              <img src="{% static 'default.png' %}" width="65%" height="65%" class="rounded-circle" alt="Default Profile Pic">
              {% endif %}
            </a>
            <p class="mt-3 h4">{{ request.user.first_name }} {{ request.user.last_name }}</p>
            <p class="mb-3">@{{ request.user.username }}</p>
          </div>

          <div>
            <!-- RIGHT SIDE: PROFILE RELATED LINKS
            {% if request.user.is_authenticated %}
            <a href="{% url 'emp:user_logout' %}" class="btn btn-danger"><i class="fas fa-right-from-bracket"></i> Logout</a>
            {% else %}
            <a href="{% url 'emp:employee_selection' %}" class="btn btn-primary"><i class="fas fa-right-to-bracket"></i> Login</a>
            {% endif %}
          </div>

        </div>
      </div>
    </div-->
  </nav>

  <div class="container-fluid p-5">
    <div class="container container-fluid">
      {% block content %}
      {% endblock %}
    </div>
  </div>
  <script src="{% static 'scripts/app.js' %}"></script>
  <script src="{% static 'bootstrap/bootstrap.min.js' %}"></script>
  <script>
    // Function to update date and time
    function updateDateTime() {
      const now = new Date();
      const date = now.toLocaleDateString('en-GB'); // dd/mm/yyyy format
      const time = now.toLocaleTimeString(); // hh:mm:ss format
      document.getElementById('datetime').textContent = `${date} ${time}`;
    }

    // Update date and time every second
    setInterval(updateDateTime, 1000);
  </script>
</body>
</html>

clientapp/templates/emp/goodbye.html
{% extends 'emp/base.html' %}
{% block title %}Good Bye from - {{block.super}}{% endblock %}

{% block content %}

<div class="p-3 p-md-5 m-md-3 text-center bg-body-tertiary border rounded-4">
  <div class="col-md-8 p-lg-5 mx-auto my-5">
    <h1 class="display-3 mb-0">Goodbye</h1>
    <h1 class="display-2 fw-bold">{{username}}</h1>
    <h3 class="fw-normal text-muted mt-4">See you again soon.</h3>
  </div>
  <p class="text-secondary-emphasis">You will be redirected to the login page in 3 seconds</p>
</div>

<script>
  setTimeout(function() {
    window.location.href = "{% url 'emp:employee_selection' %}";
  }, 3000); // waiting time in ms
</script>

{% endblock %}


clientapp/templates/emp/machine_selection.html
{% extends 'emp/base.html' %}
{% block title %}Select a Machine - {{ block.super }}{% endblock %}

{% block content %}
<style>
    /* Container adjustments */
.option-box {
    background-color: #f8f9fa;
    border: 2px solid #dee2e6;
    padding: 5%; /* Use percentage for responsive padding */
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    max-width: 90%; /* Ensure the box fits within the screen width */
    margin: 0 auto; /* Center the box */
}

/* Responsive machine buttons */
.machine-button {
    background-color: #8B0000; /* Dark red */
    color: white;
    font-size: 1.2rem; /* Relative font size for responsiveness */
    font-weight: bold;
    padding: 1.2rem 0.5rem; /* Increase padding to make buttons larger for touch */
    border-radius: 5px;
    border: none;
    cursor: pointer;
    transition: transform 0.2s ease-in-out;
    width: 100%; /* Ensure the button takes up full width of its container */
}

.machine-button:hover {
    transform: scale(1.05);
    background-color: #600000; /* Darker red on hover */
}

.machine-button-container {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(120px, 1fr)); /* Adjust the number of buttons per row dynamically */
    gap: 15px; /* Spacing between buttons */
    justify-content: center;
    margin-bottom: 30px;
}

/* Responsive back button */
.back-button {
    background-color: gray;
    color: white;
    font-size: 1.5rem;
    padding: 10px 20px;
    border-radius: 5px;
    border: none;
    cursor: pointer;
    transition: background-color 0.3s ease-in-out;
    margin-top: 20px;
}

/* Modal adjustments */
.modal-title {
    text-align: center;
    width: 100%;
}

.start-time-container {
    text-align: left;
}

.start-time-box {
    background-color: #f0f0f0;
    padding: 10px 20px;
    border-radius: 5px;
    box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.1);
    font-weight: bold;
    font-size: 16px;
    display: inline-block;
}

/* Responsive layout for smaller screens */
@media (max-width: 768px) {
    .machine-button {
        font-size: 1rem; /* Smaller font size on small screens */
        padding: 0.8rem 0.4rem; /* Smaller padding */
    }

    .machine-button-container {
        grid-template-columns: repeat(auto-fill, minmax(100px, 1fr)); /* More buttons per row on small screens */
    }

    .back-button {
        font-size: 1.2rem;
    }

    .start-time-box {
        font-size: 14px;
    }
}

    /* Center End of Task */
    .modal-title {
        text-align: center;
        width: 100%;
    }

    /* Start time container */
    .start-time-container {
        text-align: left;
    }

    .start-time-header {
        font-weight: bold;
        font-size: 18px;
        margin-bottom: 5px;
    }

    /* Oval shape for Start Time and End Work box */
    .start-time-box {
        background-color: #f0f0f0;
        padding: 10px 20px;
        border-radius: 5px; /* Oval shape */
        box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.1);
        font-weight: bold;
        font-size: 16px;
        display: inline-block; /* So that the box adjusts to content size */
    }

    .modal-footer {
        display: flex;
        justify-content: space-between; /* Align start time on left and end work button on right */
        align-items: center;
    }

    /* Oval shape for End Work button */
    .btn-danger {
        border-radius: 50px; /* Oval shape for the button */
        padding: 10px 30px; /* Adjusting padding for oval shape */
    }

    /* Oval shape for issue display */
    .issue-box {
        background-color: #e0e0e0; /* Light grey background */
        padding: 15px 30px; /* Padding for the box */
        border-radius: 50px; /* Oval shape */
        box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.1);
        text-align: center; /* Center the text */
        margin: 0 auto; /* Center the box horizontally */
        max-width: 80%; /* Maximum width for the oval box */
    }
</style>

<div class="p-3 p-md-5 m-md-3 text-center bg-body-tertiary border rounded-4">
    <div class="col-md-10 p-lg-5 mx-auto my-5 option-box">
        <h1 class="display-4 mb-5">Select a Machine</h1>
        <form method="post" action="{% url 'emp:select_machine' %}">
            {% csrf_token %}
            <div class="machine-button-container">
                <!-- Individual machine buttons without for loop -->
                <button type="submit" class="machine-button" name="machine" value="M1">M1</button>
                <button type="submit" class="machine-button" name="machine" value="M2">M2</button>
                <button type="submit" class="machine-button" name="machine" value="M3">M3</button>
                <button type="submit" class="machine-button" name="machine" value="M4">M4</button>
                <button type="submit" class="machine-button" name="machine" value="M5">M5</button>
                <button type="submit" class="machine-button" name="machine" value="M6">M6</button>
                <button type="submit" class="machine-button" name="machine" value="M7">M7</button>
                <button type="submit" class="machine-button" name="machine" value="M8">M8</button>
                <button type="submit" class="machine-button" name="machine" value="M9">M9</button>
                <button type="submit" class="machine-button" name="machine" value="M10">M10</button>
                <button type="submit" class="machine-button" name="machine" value="M11">M11</button>
                <button type="submit" class="machine-button" name="machine" value="M12">M12</button>
                <button type="submit" class="machine-button" name="machine" value="M13">M13</button>
                <button type="submit" class="machine-button" name="machine" value="M14">M14</button>
                <button type="submit" class="machine-button" name="machine" value="M15">M15</button>
                <button type="submit" class="machine-button" name="machine" value="M16">M16</button>
                <button type="submit" class="machine-button" name="machine" value="M17">M17</button>
                <button type="submit" class="machine-button" name="machine" value="M18">M18</button>
                <button type="submit" class="machine-button" name="machine" value="M19">M19</button>
                <button type="submit" class="machine-button" name="machine" value="M20">M20</button>
                <button type="submit" class="machine-button" name="machine" value="M21">M21</button>
                <button type="submit" class="machine-button" name="machine" value="M22">M22</button>
                <button type="submit" class="machine-button" name="machine" value="M23">M23</button>
                <button type="submit" class="machine-button" name="machine" value="M24">M24</button>
            </div>
                <button type="button" class="back-button" onclick="window.location.href='{% url 'emp:employee_selection' %}'">Back</button>
            </div>
        </form>
    </div>
</div>

{% if request.user.employee.is_working %}
<div class="modal fade" id="workModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="workModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="workModalLabel">END OF WORK</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <div class="issue-box">
                    {% if issue %}
                        <p>{{ issue }}</p> <!-- Display the selected issue here -->
                    {% else %}
                        <p>No issue selected.</p> <!-- Fallback if no issue is available -->
                    {% endif %}
                </div>
            </div>

            <div class="modal-footer">
                <!-- Start Time on the left -->
                <div class="start-time-container">
                    <div class="start-time-header">START WORK</div>
                    <div class="start-time-box">{{ request.user.employee.worksession_set.last.start_time|date:"h:i A" }}</div>
                </div>

                <!-- End Work Button on the right -->
                <form method="POST" action="{% url 'emp:temp_end_work' %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">END WORK</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    document.addEventListener("DOMContentLoaded", function () {
        var workModal = new bootstrap.Modal(document.getElementById('workModal'));
        workModal.show();
    });
</script>
{% endif %}

{% endblock %}